// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyBWeEUQZphQd9R1R8icsEUO1Iw_MslVaME',
//     appId: '1:110184646423:web:dd153d27acd9d732bad952',
//     messagingSenderId: '110184646423',
//     projectId: 'beauty-hub-32a6c',
//     authDomain: 'beauty-hub-32a6c.firebaseapp.com',
//     storageBucket: 'beauty-hub-32a6c.firebasestorage.app',
//     measurementId: 'G-60RGB23XY3',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyDXCUQLgl9VgnI_WTibjMTk6_fitEnRmNE',
//     appId: '1:110184646423:android:f3ff97a73e631025bad952',
//     messagingSenderId: '110184646423',
//     projectId: 'beauty-hub-32a6c',
//     storageBucket: 'beauty-hub-32a6c.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyCMFgcwmV4W8L8YpZ5gDVREP9XYMrgjYpA',
//     appId: '1:110184646423:ios:16a60f3c862f2de3bad952',
//     messagingSenderId: '110184646423',
//     projectId: 'beauty-hub-32a6c',
//     storageBucket: 'beauty-hub-32a6c.firebasestorage.app',
//     iosBundleId: 'com.example.projectUser',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyCMFgcwmV4W8L8YpZ5gDVREP9XYMrgjYpA',
//     appId: '1:110184646423:ios:16a60f3c862f2de3bad952',
//     messagingSenderId: '110184646423',
//     projectId: 'beauty-hub-32a6c',
//     storageBucket: 'beauty-hub-32a6c.firebasestorage.app',
//     iosBundleId: 'com.example.projectUser',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyBWeEUQZphQd9R1R8icsEUO1Iw_MslVaME',
//     appId: '1:110184646423:web:02aa95b844e6d800bad952',
//     messagingSenderId: '110184646423',
//     projectId: 'beauty-hub-32a6c',
//     authDomain: 'beauty-hub-32a6c.firebaseapp.com',
//     storageBucket: 'beauty-hub-32a6c.firebasestorage.app',
//     measurementId: 'G-D7HS01DW33',
//   );
// }
